config/routes.rb
Rails.application.routes.draw do
  get 'students/:id/payments/new' => 'payments#new', as: :new_student_payment
  get 'students/:id/payments' => 'students#payments', as: :student_payments
  get 'checks/new' => redirect('/checks')
  get 'stripes/new' => redirect('/stripes')
  get 'loans/new' => redirect('/loans')
  get 'wires/new' => redirect('/wires')
  get 'webhooks/stripe_webhook' => redirect('/')
  get 'performance_charts/new' => redirect('performance_charts')
  get 'payments' => 'payments#index', as: :payments
  post 'twilio/voice' => 'twilio#voice'
  post 'students/:student_id/:payment_type/:id/notify' => 'notifications#notify', as: :payment_notification
  post 'stripe/deposit' => 'webhooks#stripe_webhook'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cohorts
  resources :performance_charts
  resources :stripes
  resources :wires
  resources :checks
  resources :loans
  resources :students

  root 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :cohort
  has_many :loans
  has_many :checks
  has_many :wires
  has_many :stripes
  before_create :calculate_balance
  before_destroy :destroy_payments


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 25 }
  # validates :phone_num, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def payments
     loans + checks + stripes + wires
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def calculate_balance(deposit=0)
    self.balance -= discount
    self.balance -= deposit
  end

  def discount_difference(params)
    self.discount - params["discount"].to_i
  end

  private
  def destroy_payments
    loans.destroy_all
    checks.destroy_all
    stripes.destroy_all
    wires.destroy_all
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :payments]
  before_filter :authenticate_user!
  before_filter :set_cohort, only: :index
  before_filter :set_location, only: :index
  before_filter :default_filter, only: :index
  before_action :check_admin, except: [:index, :show]


  def payments
  end

  # GET /students
  # GET /students.json
  def index
    @default_students_filter = false
    @all_students_filter = false
    @cohort_students_filter = false
    @location_students_filter = false
    @balance_students_filter = false
    @unspecified_students = Student.where(cohort_id: nil)
    @all_students = Student.all.order(created_at: :asc)
    filters
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    # @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      difference = @student.discount_difference(student_params)
      if @student.update(student_params)
        @student.balance = @student.balance + difference
        @student.save
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Student was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def filters
      if @cohort.present?
        @filtered_students = @cohort.students
        @cohort_students_filter = true
      elsif @location.present?
        @filtered_students = @location.map(&:students)
        @filtered_students.flatten!
        @location_students_filter = true
      elsif params[:student].present? && params[:student][:balance].present?
        if params[:student][:balance] == "Outstanding"
          @filtered_students = Student.where("balance > ?", 0).order(balance: :desc)
        elsif params[:student][:balance] == "Cleared"
          @filtered_students = Student.where(balance: 0)
        end
        @balance_students_filter = true
      else
        if (request.original_url.include?("/students") && !request.original_url.include?("?")) || Cohort.all.length == 0 || Student.all.length == 0
          @filtered_students = @all_students
          @all_students_filter = true
        else
          @filtered_students = @default_cohort.students
          @default_students_filter = true
        end
      end
    end

    def default_filter
      if Cohort.where("start_date >= ?", Date.today).empty?
        @default_cohort = Cohort.where("start_date <= ?", Date.today).order(start_date: :desc).first
      else
        @default_cohort = Cohort.where("start_date >= ?", Date.today).first
      end
    end

    def set_student
      @student = Student.find(params[:id])
    end

    def set_cohort
        @cohort = Cohort.find_by(id: params[:cohort][:id]) if params[:cohort].present? && params[:cohort][:id].present?
    end

    def set_location
        @location = Cohort.where(location: params[:cohort][:location]) if params[:cohort].present? && params[:cohort][:location].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :phone_num, :balance, :discount, :notes, :cohort_id, :facebook, :twitter, :linkedin, :github, :portfolio_url, :final_project_url)
    end

    def check_admin
      if current_user.try(:admin?) == false
        redirect_to root_path, notice: "You are not authorized to take that action"
      end
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_create_bal_disc.html.erb
<div class="field">
  <%= f.label :discount %><br>
  <%= f.number_field :discount, value: 0 %>
</div>
<div class="field">
  <%= f.label :balance %><br>
  <%= f.number_field :balance, value: 10000 %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="login text-center">
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone_num, 'Phone Number' %><br>
      <%= f.text_field :phone_num %>
    </div>
    <% if @student.id.nil? %>
      <%= render 'create_bal_disc', f: f %>
    <% else %>
      <%= render 'update_discount', f: f %>
    <% end %>
    <div class="field">
      <%= f.label :facebook, 'Facebook' %><br>
      <%= f.text_field :facebook %>
    </div>
    <div class="field">
      <%= f.label :twitter, 'Twitter' %><br>
      <%= f.text_field :twitter %>
    </div>
    <div class="field">
      <%= f.label :linkedin, 'LinkedIn' %><br>
      <%= f.text_field :linkedin %>
    </div>
    <div class="field">
      <%= f.label :github, 'GitHub' %><br>
      <%= f.text_field :github %>
    </div>
    <div class="field">
      <%= f.label :portfolio_url, 'Portfolio URL' %><br>
      <%= f.text_field :portfolio_url %>
    </div>
    <div class="field">
      <%= f.label :final_project_url, 'Final Project URL' %><br>
      <%= f.text_field :final_project_url %>
    </div>
    <div class="field">
      <%= f.label :notes %><br>
      <%= f.text_area :notes %>
    </div>
    <div class="field">
      <%= f.label :cohort_id %><br>
      <%= f.select :cohort_id, Cohort.all.collect { |c| [c.name, c.id] }, {include_blank: 'Unspecified'}, class: 'btn' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/students/_student_collection.html.erb
<div class="table-responsive col-md-12">
  <table class="table table-striped table-hover student-list">
    <thead>
      <tr>
        <% if current_user.admin? %>
          <th>Cohort</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Phone Number</th>
          <th>Balance</th>
        <% else %>
          <th class="instructor-th">Cohort</th>
          <th class="instructor-th">Full Name</th>
          <th class="instructor-th">Email</th>
          <th class="instructor-th">Phone Number</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @filtered_students.each do |student| %>
        <% if student.cohort.present? %>
          <tr>
            <% if current_user.admin? %>
              <td><%= link_to "#{student.cohort.name}", student.cohort %></td>
              <td><%= link_to "#{student.full_name}", student %></td>
              <td><%= student.email %></td>
              <td><%= number_to_phone(student.phone_num) %></td>
              <% if student.balance == 0 %>
                <td class="payments_color_blue"><%= number_to_currency(student.balance) %></td>
              <% elsif student.balance > 0 %>
                <td class="payments_color_orange"><%= number_to_currency(student.balance) %></td>
              <% else %>
                <td><%= number_to_currency(student.balance) %></td>
              <% end %>
              <td><%= link_to 'View Payments', student_payments_path(student) %></td>
              <td><%= link_to 'Remove Student', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td class="instructor-td"><%= link_to "#{student.cohort.name}", student.cohort %></td>
              <td class="instructor-td"><%= link_to "#{student.full_name}", student %></td>
              <td class="instructor-td"><%= student.email %></td>
              <td class="instructor-td"><%= number_to_phone(student.phone_num) %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/_unspecified_students.html.erb
<div class="row col-md-12">
  <div class="text-center">
    <h2 class="header-title">Students Without Cohort</h2>
  </div>
</div>

<div class="table-responsive col-md-12">
  <table class="table table-striped table-hover student-list">
    <thead>
      <tr>
        <% if current_user.admin? %>
          <th>Cohort</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Phone Number</th>
          <th>Balance</th>
        <% else %>
          <th class="instructor-th">Cohort</th>
          <th class="instructor-th">Full Name</th>
          <th class="instructor-th">Email</th>
          <th class="instructor-th">Phone Number</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @unspecified_students.each do |student| %>
        <tr>
          <% if current_user.admin? %>
            <td><%= link_to 'None', edit_student_path(student) %></td>
            <td><%= link_to "#{student.full_name}", student %></td>
            <td><%= student.email %></td>
            <td><%= number_to_phone(student.phone_num) %></td>
            <% if student.balance == 0 %>
              <td class='payments_color_blue'><%= number_to_currency(student.balance) %></td>
            <% elsif student.balance > 0 %>
              <td class='payments_color_orange'><%= number_to_currency(student.balance) %></td>
            <% else %>
              <td><%= number_to_currency(student.balance) %></td>
            <% end %>
            <td><a href="https://docs.google.com/a/wyncode.co/spreadsheets/d/1n1lLJlgHSLdfrG0zx9dDsqISUwOfne1QN9VPC8tQj1w/edit?usp=sharing" target="_blank">View Form</a></td>
            <td><%= link_to 'View Payments', student_payments_path(student) %></td>
            <td><%= link_to 'Remove Student', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td class="instructor-td">None </td>
            <td class="instructor-td"><%= link_to "#{student.full_name}", student %></td>
            <td class="instructor-td"><%= student.email %></td>
            <td class="instructor-td"><%= number_to_phone(student.phone_num) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/_update_bal_disc.html.erb
<div class="field">
  <%= f.label :discount %><br>
  <%= f.number_field :discount, value: @student.discount %>
</div>
<div class="field">
  <%= f.label :balance %><br>
  <%= f.number_field :balance, value: @student.balance %>
</div>

app/views/students/_update_discount.html.erb
<div class="field">
  <%= f.label :discount %><br>
  <%= f.number_field :discount, value: @student.discount  %>
</div>

app/views/students/edit.html.erb
<div class="container">
    <div class="row">
      <%= link_to 'Show', @student, class: " btn btn-info btn-text-color", id:"student-edit-show-btn" %>
  </div>
</div>

<h1>Edit Student</h1>
<%= render 'form' %>

app/views/students/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<% nil_cohort = false %>
<% @all_students.each do |student| %>
  <% if student.cohort.present? == false %>
    <% nil_cohort = true %>
  <% end %>
<% end %>

<div class="text-center">
  <form class="student-filters">
    <%= select("cohort", "id", Cohort.all.collect {|c| [c.name, c.id ]}, {include_blank: 'Cohort'}, class: "btn", id: "student-list-btn-bckgrd") %>
      <input type="submit" value="Filter" class="btn btn-info" />
  </form>
  <form class="student-filters">
    <%= select("cohort", "location", Cohort.all.collect(&:location).uniq, {include_blank: 'Location'}, class: "btn", id: "student-list-btn-bckgrd") %>
    <input type="submit" value="Filter" class="btn btn-info" />
  </form>
  <% if current_user.admin? %>
    <form class="student-filters">
      <%= select("student", "balance", ["Outstanding", "Cleared"], {include_blank: 'Balance'}, class: "btn", id: "student-list-btn-bckgrd") %>
      <input type="submit" value="Filter" class="btn btn-info" />
    </form>
</div>

<% end %>

<% if nil_cohort == true %>
  <%= render 'unspecified_students' %>
<% end %>

<br>

<div class="row col-md-12">
  <div class="text-center">
    <div class="index-header">
      <h2 class="header-title">
      <% if @cohort_students_filter == true %>
        <%= Cohort.find(params[:cohort][:id].to_i).name %>
      <% elsif @location_students_filter == true %>
        <%= Cohort.find_by(location: params[:cohort][:location]).location %>
      <% elsif @balance_students_filter == true %>
        <%= params[:student][:balance] %>
      <% else %>
        <% if @default_students_filter == true %>
          <%= @default_cohort.name %>
        <% elsif @all_students_filter == true  %>
          All
        <% end %>
      <% end %>
      Students</h2>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <% if @all_students_filter == false %>
            <%= link_to "View All Students", students_path, class: " btn btn-info", id: "all-students-btn" %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to 'New Student', new_student_path, class: " btn btn-info", id: "new-student-add-btn" %>
          <% end %>
        </div>
        <% if @cohort_students_filter == true %>
          <h3 id="capacity" class="text-center"><strong>Capacity:</strong> <%= Cohort.find(params[:cohort][:id].to_i).capacity %> <strong>Available:</strong> <%= Cohort.find(params[:cohort][:id].to_i).capacity - Cohort.find(params[:cohort][:id].to_i).students.count %></h3>
        <% elsif @default_students_filter == true %>
          <h3 id="capacity" class="text-center"><strong>Capacity:</strong> <%= @default_cohort.capacity %> <strong>Available:</strong> <%= @default_cohort.capacity - @default_cohort.students.count %></h3>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

<%= render 'student_collection' %>

<br>

app/views/students/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h2>New Student</h2>
  </div>
</div>

<%= render 'form' %>

<div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to 'Back', root_path, class: " btn btn-info", id: "new-student-back-btn" %>
      </div>
    </div>
</div>

app/views/students/payments.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
  <%= link_to("Student Profile", @student, :class => 'btn btn-large btn-info btn-text-color left-side-btn-offset') %>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <div id="payment-listing">
      <h2 id="student-payment-header-title">Payments For <%= @student.full_name %></h2>
      <div class="row new-payment col-md-12 text-center">
        <%= link_to('New Payment', new_student_payment_path(@student), :class => 'btn btn-large btn-info', id: "new-payment-button-paypage") %>
        <h3 class="text-center" id="balance-counter"><strong>Balance:</strong> <%= number_to_currency(@student.balance) %></h3>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive col-md-8 col-md-offset-2">
  <table class="table">
    <thead>
      <tr class="well">
        <th>Payment Date</th>
        <th>Payment Type</th>
        <th>Amount</th>
        <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <% @student.payments.each do |payment| %>
        <tr>
          <td><%= payment.pay_date.strftime("%m/%d/%Y") %></td>
          <td><%= payment.class %></td>
          <td><%= number_to_currency(payment.amount) %></td>
          <% payment_type = payment.class.to_s.downcase %>
          <td><%= link_to "Notify", payment_notification_path(@student.id, payment_type, payment), method: :post, data: {confirm: "Are you sure you want to text #{@student.full_name} about this #{payment.class.to_s.downcase} payment?"} %></td>
          <td><%= link_to "Details", payment %></td>
          <td><%= link_to 'Remove', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/students/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
  <div id="new-student-back_btn">
    <%= link_to 'View Payments', student_payments_path(@student), class: "btn btn-info btn-text-color", id: "student-detail-back-btn" %>
  </div>
</div>

<div class="row span12">
  <div class="panel panel-default student-list-detail ">
    <div class="panel-heading">
      <strong>Cohort:</strong>
    </div>
      <div class="panel-body">
        <% if @student.cohort.present? %>
          <%= @student.cohort.name %>
        <% else %>
          Unspecified
        <% end %>
      </div>
    <div class="panel-heading">
      <strong>First name:</strong>
    </div>
      <div class="panel-body">
        <%= @student.first_name %>
      </div>
    <div class="panel-heading">
      <strong>Last name:</strong>
    </div>
      <div class="panel-body">
        <%= @student.last_name %>
      </div>
    <div class="panel-heading">
      <strong>Email:</strong>
    </div>
      <div class="panel-body">
        <%= @student.email %>
      </div>
    <div class="panel-heading">
      <strong>Phone number:</strong>
    </div>
      <div class="panel-body">
        <%= number_to_phone(@student.phone_num) %>
      </div>
    <% if current_user.admin? %>
      <div class="panel-heading">
        <strong>Discount:</strong>
      </div>
        <div class="panel-body">
          <%= number_to_currency(@student.discount) %>
        </div>
      <div class="panel-heading">
          <strong>Balace:</strong>
      </div>
      <% if @student.balance == 0 %>
        <div class="panel-body payments_color_blue">
          <%= number_to_currency(@student.balance) %>
        </div>
      <% elsif @student.balance > 0 %>
        <div class="panel-body payments_color_orange">
          <%= number_to_currency(@student.balance) %>
        </div>
      <% else %>
        <div class="panel-body">
          <%= number_to_currency(@student.balance) %>
        </div>
      <% end %>
    <% end %>
    <div class="panel-heading">
      <strong>Facebook:</strong>
    </div>
      <div class="panel-body">
        <%= @student.facebook %>
      </div>
    <div class="panel-heading">
      <strong>Twitter:</strong>
    </div>
      <div class="panel-body">
        <%= @student.twitter %>
      </div>
    <div class="panel-heading">
      <strong>LinkedIn:</strong>
    </div>
      <div class="panel-body">
        <%= @student.linkedin %>
      </div>
    <div class="panel-heading">
      <strong>Github:</strong>
    </div>
      <div class="panel-body">
        <%= @student.github %>
      </div>
    <div class="panel-heading">
      <strong>Portfolio URL:</strong>
    </div>
      <div class="panel-body">
        <%= @student.portfolio_url %>
      </div>
    <div class="panel-heading">
      <strong>Final Project URL:</strong>
    </div>
      <div class="panel-body">
        <%= @student.final_project_url %>
      </div>
    <div class="panel-heading">
      <strong>Notes:</strong>
    </div>
      <div class="panel-body">
        <%= @student.notes %>
      </div>
  </div>
</div>

<% if current_user.admin? %>
  <div class="row span12">
    <div class="text-center">
    <%= link_to 'Edit', edit_student_path(@student), class: " btn btn-info", id: "student-detail-edit-btn" %>
    </div>
  </div>
<% end %>