config/routes.rb
Rails.application.routes.draw do
  get 'students/:id/payments/new' => 'payments#new', as: :new_student_payment
  get 'students/:id/payments' => 'students#payments', as: :student_payments
  get 'checks/new' => redirect('/checks')
  get 'stripes/new' => redirect('/stripes')
  get 'loans/new' => redirect('/loans')
  get 'wires/new' => redirect('/wires')
  get 'webhooks/stripe_webhook' => redirect('/')
  get 'performance_charts/new' => redirect('performance_charts')
  get 'payments' => 'payments#index', as: :payments
  post 'twilio/voice' => 'twilio#voice'
  post 'students/:student_id/:payment_type/:id/notify' => 'notifications#notify', as: :payment_notification
  post 'stripe/deposit' => 'webhooks#stripe_webhook'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cohorts
  resources :performance_charts
  resources :stripes
  resources :wires
  resources :checks
  resources :loans
  resources :students

  root 'students#index'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :check_admin

  def new
    @student = Student.find(params[:id])
    @loan = Loan.new
    @check = Check.new
    @wire = Wire.new
    @stripe = Stripe.new
  end

  def index
    @payments = Student.all.map{ |s| s.payments }.flatten.sort_by(&:pay_date).reverse!
  end
  private
  def check_admin
    if current_user.try(:admin?) == false
      redirect_to root_path, notice: "You are not authorized to take that action"
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="row">
  <div class="col-md-12 text-center">
      <h2>Create A New Payment for <%= @student.full_name %> </h2>
    </div>
</div>


<div class="row" id="payment-type-selector">
  <div class="col-md-12">
    <div class="input-group" id="payment_type">

      <form id="payment_type">
        <label class="input-group-addon">
          <input type="radio" name="payment_type" value="loan">   Loan<br>
        </label>
        <label class="input-group-addon">
          <input type="radio" name="payment_type" value="check" class="check">   Check<br>
        </label>
        <label class="input-group-addon">
          <input type="radio" name="payment_type" value="stripe">   Stripe<br>
        </label>
        <label class="input-group-addon">
          <input type="radio" name="payment_type" value="wire">   Wire
        </label>
      </form>
    </div>
  </div>
</div>

<div id="payment_render">
  <%= render 'loans/form' %>
  <%= render 'checks/form' %>
  <%= render 'stripes/form' %>
  <%= render 'wires/form' %>
</div>

app/views/payments/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
  <div class="col-md-12 text-center">
    <div id="payment-listing">
      <h2>All Payments</h2>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-12 text-center">
      <div class="btn-group " role="group" id="listing-payments-btn-group">
        <div button type="button" class="btn btn-info">
          <%= link_to('Stripes', stripes_path, class: "btn-text-color") %>
        </div>
        <div button type="button" class="btn btn-info">
          <%= link_to('Loans', loans_path, class: "btn-text-color") %>
        </div>
        <div button type="button" class="btn btn-info">
          <%= link_to('Checks', checks_path, class: "btn-text-color") %>
        </div>
        <div button type="button" class="btn btn-info">
          <%= link_to('Wires', wires_path, class: "btn-text-color") %>
        </div>
      </div>
    </div>
</div>

<div class="table-responsive col-md-8 col-md-offset-2">
  <table class="table table-hover">
    <thead>
      <tr class="well">
        <th>Payment Date</th>
        <th>Student</th>
        <th>Payment Type</th>
        <th>Amount</th>
        <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.pay_date.strftime("%m/%d/%Y") %></td>
          <td><%= payment.student.full_name %></td>
          <td><%= payment.class %></td>
          <td><%= number_to_currency(payment.amount) %></td>
          <td><%= link_to "Details", payment %></td>
          <td><%= link_to 'Remove', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/payments/new.html.erb
<div class="container">
    <div class="row">
        <%= link_to "#{@student.full_name} Payments", student_payments_path(@student), class: " btn btn-info", id: "create-pay-back-btn" %>
    </div>
</div>


<div id="new-payment-creation">
  <%= render 'form' %>
</div>