config/routes.rb
Rails.application.routes.draw do
  get 'students/:id/payments/new' => 'payments#new', as: :new_student_payment
  get 'students/:id/payments' => 'students#payments', as: :student_payments
  get 'checks/new' => redirect('/checks')
  get 'stripes/new' => redirect('/stripes')
  get 'loans/new' => redirect('/loans')
  get 'wires/new' => redirect('/wires')
  get 'webhooks/stripe_webhook' => redirect('/')
  get 'performance_charts/new' => redirect('performance_charts')
  get 'payments' => 'payments#index', as: :payments
  post 'twilio/voice' => 'twilio#voice'
  post 'students/:student_id/:payment_type/:id/notify' => 'notifications#notify', as: :payment_notification
  post 'stripe/deposit' => 'webhooks#stripe_webhook'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cohorts
  resources :performance_charts
  resources :stripes
  resources :wires
  resources :checks
  resources :loans
  resources :students

  root 'students#index'

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :student
  before_create :set_name_on_check

  def set_name_on_check
    if name_on_check.blank?
      self.name_on_check = self.student.full_name
    end
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]
  before_action :check_admin


  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
    @student = @check.student
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    respond_to do |format|
      if @check.save
        @check.student.balance = (@check.student.balance) - @check.amount
        @check.student.save
        format.html { redirect_to student_payments_path(@check.student), notice: 'Check was successfully created.' }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      old_amount = @check.amount
      new_amount = check_params["amount"].to_i
      diff = old_amount - new_amount
      if @check.update(check_params)
        @check.student.balance = @check.student.balance + diff
        @check.student.save
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    @check.student.balance = @check.student.balance + @check.amount
    @check.student.save
    respond_to do |format|
      format.html { redirect_to student_payments_path(@check.student), notice: 'Check was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:student_id, :amount, :pay_date, :deposited_date, :check_number, :name_on_check)
    end

    def check_admin
      if current_user.try(:admin?) == false
        redirect_to root_path, notice: "You are not authorized to take that action"
      end
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_for @check, html: {class: "new_check new_payment"} do |f| %>
  <% if @check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% @check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class='row span12'>
  <div class='new-payment-field text-center dropshadow'>
      <div class="field top-label-element">
        <%= f.hidden_field :student_id, value: @student.id %>
      </div>
      <div class="field">
        <%= f.label :amount %><br>
        <%= f.number_field :amount, step: 0.01 %>
      </div>
      <div class="field">
        <%= f.label :pay_date, "Date Received" %><br>
        <%= f.date_field :pay_date %>
      </div>
      <div class="field">
        <%= f.label :deposited_date, "Deposited Date" %><br>
        <%= f.date_field :deposited_date %>
      </div>
      <div class="field">
        <%= f.label :check_number, "Check Number" %><br>
        <%= f.number_field :check_number %>
      </div>
      <div class="field">
        <%= f.label :name_on_check, "Name On Check" %><br>
        <%= f.text_field :name_on_check %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/checks/edit.html.erb
<div class="container">
    <div class="row">
      <!-- <div class="col-md-12"> -->
        <%= link_to 'Show', @check, class: "btn btn-info btn-text-color", id: "check-edit-show-btn-left-margin" %>
        <%= link_to 'Back', checks_path, class: "btn btn-info btn-text-color" %>
      <!-- </div> -->
    </div>
</div>

<h1>Edit Check</h1>

<%= render 'form' %>

app/views/checks/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="btn-group loan-listing-back-btns" role="group">
  <button type="button" class="btn btn-info">
    <%= link_to('To Students', root_path, class: "button-color-white")%>
  </button>
  <button type="button" class="btn btn-info">
    <%= link_to('All Payments', payments_path, class: "button-color-white") %>
  </button>
</div>

<h1>Check Payments</h1>
<div class="table-responsive col-md-8 col-md-offset-2">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Student</th>
        <th>Amount</th>
        <th>Date Received</th>
        <th>Deposited Date</th>
        <th>Check Number</th>
        <th>Name on Check</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @checks.each do |check| %>
        <tr>
          <td><%= check.student.first_name %> <%= check.student.last_name %></td>
          <td><%= number_to_currency(check.amount) %></td>
          <td><%= check.pay_date.strftime("%m/%d/%Y") %></td>
          <td><%= check.deposited_date.strftime("%m/%d/%Y") %></td>
          <td><%= check.check_number %></td>
          <td><%= check.name_on_check %></td>
          <td><%= link_to 'Show', check %></td>
          <td><%= link_to 'Edit', edit_check_path(check) %></td>
          <td><%= link_to 'Remove', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/checks/new.html.erb
<h1>New Check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">
    <div class="row">
          <%= link_to 'Back', checks_path, class: "btn btn-info btn-text-color", id: "check-show-back-btn-left-margin" %>
    </div>
</div>

<div class="row span12">
  <div class="new-payment-field text-center ">
    <p>
      <strong>Student:</strong>
      <%= @check.student.first_name %>
      <%= @check.student.last_name %>
    </p>
    <p>
      <strong>Amount:</strong>
      <%= number_to_currency(@check.amount) %>
    </p>
    <p>
      <strong>Date Received:</strong>
      <%= @check.pay_date.strftime("%m/%d/%Y") %>
    </p>
    <p>
      <strong>Deposited Date:</strong>
      <%= @check.deposited_date.strftime("%m/%d/%Y") %>
    </p>
    <p>
      <strong>Check Number:</strong>
      <%= @check.check_number %>
    </p>
    <p>
      <strong>Name on Check:</strong>
        <%= @check.name_on_check %>
    </p>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
          <%= link_to 'Edit', edit_check_path(@check), class: "btn btn-info btn-text-color" %>
      </div>
    </div>
</div>