config/routes.rb
Rails.application.routes.draw do
  get 'students/:id/payments/new' => 'payments#new', as: :new_student_payment
  get 'students/:id/payments' => 'students#payments', as: :student_payments
  get 'checks/new' => redirect('/checks')
  get 'stripes/new' => redirect('/stripes')
  get 'loans/new' => redirect('/loans')
  get 'wires/new' => redirect('/wires')
  get 'webhooks/stripe_webhook' => redirect('/')
  get 'performance_charts/new' => redirect('performance_charts')
  get 'payments' => 'payments#index', as: :payments
  post 'twilio/voice' => 'twilio#voice'
  post 'students/:student_id/:payment_type/:id/notify' => 'notifications#notify', as: :payment_notification
  post 'stripe/deposit' => 'webhooks#stripe_webhook'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cohorts
  resources :performance_charts
  resources :stripes
  resources :wires
  resources :checks
  resources :loans
  resources :students

  root 'students#index'

end

app/models/stripe.rb
class Stripe < ActiveRecord::Base
  belongs_to :student
end

app/controllers/stripes_controller.rb
class StripesController < ApplicationController
  before_action :set_stripe, only: [:show, :edit, :update, :destroy]
  before_action :check_admin


  # GET /stripes
  # GET /stripes.json
  def index
    @stripes = Stripe.all
  end

  # GET /stripes/1
  # GET /stripes/1.json
  def show
  end

  # GET /stripes/new
  def new
    @stripe = Stripe.new
  end

  # GET /stripes/1/edit
  def edit
    @student = @stripe.student
  end

  # POST /stripes
  # POST /stripes.json
  def create
    @stripe = Stripe.new(stripe_params)

    respond_to do |format|
      if @stripe.save
        @stripe.student.balance = (@stripe.student.balance) - @stripe.amount
        @stripe.student.save
        format.html { redirect_to student_payments_path(@stripe.student), notice: 'Stripe was successfully created.' }
        format.json { render :show, status: :created, location: @stripe }
      else
        format.html { render :new }
        format.json { render json: @stripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stripes/1
  # PATCH/PUT /stripes/1.json
  def update
    respond_to do |format|
      old_amount = @stripe.amount
      new_amount = stripe_params["amount"].to_i
      diff = old_amount - new_amount
      if @stripe.update(stripe_params)
        @stripe.student.balance = @stripe.student.balance + diff
        @stripe.student.save
        format.html { redirect_to @stripe, notice: 'Stripe was successfully updated.' }
        format.json { render :show, status: :ok, location: @stripe }
      else
        format.html { render :edit }
        format.json { render json: @stripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stripes/1
  # DELETE /stripes/1.json
  def destroy
    @stripe.destroy
    @stripe.student.balance = @stripe.student.balance + @stripe.amount
    @stripe.student.save
    respond_to do |format|
      format.html { redirect_to student_payments_path(@stripe.student), notice: 'Stripe was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stripe
      @stripe = Stripe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stripe_params
      params.require(:stripe).permit(:student_id, :amount, :refunded, :pay_date)
    end

    def check_admin
      if current_user.try(:admin?) == false
        redirect_to root_path, notice: "You are not authorized to take that action"
      end
    end
end

app/helpers/stripes_helper.rb
module StripesHelper
end

app/views/stripes/_form.html.erb
<%= form_for @stripe, html: {class: "new_stripe new_payment"} do |f| %>
  <% if @stripe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stripe.errors.count, "error") %> prohibited this stripe from being saved:</h2>

      <ul>
      <% @stripe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row span12">
  <div class="new-payment-field text-center">
    <div class="field top-label-element">
      <%= f.hidden_field :student_id, value: @student.id %>
    </div>
    <div class="field">
      <%= f.label :amount %><br>
      <%= f.number_field :amount, step: 0.01 %>
    </div>
    <div class="field">
      <%= f.label :pay_date %><br>
      <%= f.date_field :pay_date %>
    </div>
    <div class="field">
      <%= f.label :refunded %><br>
      <%= f.check_box :refunded %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

app/views/stripes/edit.html.erb
<div class="container">
    <div class="row">
        <%= link_to 'Show', @stripe, class: "btn btn-info button-color-white", id: "editing-stripe-show-btn" %>
        <%= link_to 'Back', stripes_path, class: "btn btn-info button-color-white" %>
    </div>
</div>
<h1>Edit Stripe</h1>
<%= render 'form' %>

app/views/stripes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="btn-group loan-listing-back-btns" role="group">
  <button type="button" class="btn btn-info">
    <%= link_to('To Students', root_path, class: "button-color-white")%>
  </button>
  <button type="button" class="btn btn-info">
    <%= link_to('All Payments', payments_path, class: "button-color-white") %>
  </button>
</div>

<h1>Stripe Payments</h1>

<div class="table-responsive col-md-8 col-md-offset-2">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Student</th>
        <th>Amount</th>
        <th>Pay Date</th>
        <th>Refunded?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @stripes.each do |stripe| %>
        <tr>
          <td><%= stripe.student.full_name %></td>
          <td><%= number_to_currency(stripe.amount) %></td>
          <td><%= stripe.pay_date.strftime("%m/%d/%Y") %></td>
          <td><%= stripe.refunded %></td>
          <td><%= link_to 'Show', stripe %></td>
          <td><%= link_to 'Edit', edit_stripe_path(stripe) %></td>
          <td><%= link_to 'Remove', stripe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stripes/new.html.erb
<h1>New Stripe</h1>

<%= render 'form' %>

<%= link_to 'Back', stripes_path %>

app/views/stripes/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container">
    <div class="row">
      <%= link_to 'Back', stripes_path, class: "btn btn-info button-color-white", id:"stripes-show-back-btn" %>
    </div>
</div>

<div class="row span12">
  <div class="new-payment-field text-center ">
    <p>
      <strong>Student:</strong>
      <%= @stripe.student.full_name %>
    </p>
    <p>
      <strong>Amount:</strong>
      <%= number_to_currency(@stripe.amount) %>
    </p>
    <p>
      <strong>Refunded:</strong>
      <%= @stripe.refunded %>
    </p>
    <p>
      <strong>Pay Date:</strong>
      <%= @stripe.pay_date.strftime("%m/%d/%Y") %>
    </p>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
          <%= link_to 'Edit', edit_stripe_path(@stripe), class: "btn btn-info button-color-white", id: "stripes-show-edit-btn"  %>
      </div>
    </div>
</div>